export const {
    VITE_AWS_REGION,
    VITE_USER_POOL_ID,
    VITE_APP_CLIENT_ID,
    VITE_COGNITO_DOMAIN,
    VITE_REDIRECT_SIGN_IN,
    VITE_REDIRECT_SIGN_OUT,
    VITE_APP_CLIENT_SECRET,
} = import.meta.env;