"""create vehicles table

Revision ID: 3509d28a6a79
Revises: 
Create Date: 2025-05-06 13:28:35.127002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3509d28a6a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lot_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auction_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('delivery_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('shipping_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price_delivery', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('price_shipping', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cognito_sub', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey')
    )
    # ### end Alembic commands ###
